/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AuthVerifyOtpRouteImport } from './routes/auth/verify-otp'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AdminLayoutRouteImport } from './routes/admin/_layout'
import { Route as AppTrackRouteImport } from './routes/_app/track'
import { Route as AppCheckoutRouteImport } from './routes/_app/checkout'
import { Route as AppCartRouteImport } from './routes/_app/cart'
import { Route as AppAccountRouteImport } from './routes/_app/account'
import { Route as AdminLayoutIndexRouteImport } from './routes/admin/_layout/index'
import { Route as AppProductsIndexRouteImport } from './routes/_app/products/index'
import { Route as AppOrdersIndexRouteImport } from './routes/_app/orders/index'
import { Route as AppProductsSlugRouteImport } from './routes/_app/products/$slug'
import { Route as AppOrdersIdRouteImport } from './routes/_app/orders/$id'
import { Route as AdminLayoutUsersIndexRouteImport } from './routes/admin/_layout/users/index'
import { Route as AdminLayoutProductsIndexRouteImport } from './routes/admin/_layout/products/index'
import { Route as AdminLayoutOrdersIndexRouteImport } from './routes/admin/_layout/orders/index'
import { Route as AdminLayoutInventoryIndexRouteImport } from './routes/admin/_layout/inventory/index'
import { Route as AdminLayoutCategoriesIndexRouteImport } from './routes/admin/_layout/categories/index'
import { Route as AdminLayoutProductsIdRouteImport } from './routes/admin/_layout/products/$id'
import { Route as AdminLayoutOrdersIdRouteImport } from './routes/admin/_layout/orders/$id'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AuthVerifyOtpRoute = AuthVerifyOtpRouteImport.update({
  id: '/auth/verify-otp',
  path: '/auth/verify-otp',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLayoutRoute = AdminLayoutRouteImport.update({
  id: '/admin/_layout',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTrackRoute = AppTrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => AppRoute,
} as any)
const AppCheckoutRoute = AppCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => AppRoute,
} as any)
const AppCartRoute = AppCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountRoute = AppAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppRoute,
} as any)
const AdminLayoutIndexRoute = AdminLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AppProductsIndexRoute = AppProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersIndexRoute = AppOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsSlugRoute = AppProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersIdRoute = AppOrdersIdRouteImport.update({
  id: '/orders/$id',
  path: '/orders/$id',
  getParentRoute: () => AppRoute,
} as any)
const AdminLayoutUsersIndexRoute = AdminLayoutUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutProductsIndexRoute =
  AdminLayoutProductsIndexRouteImport.update({
    id: '/products/',
    path: '/products/',
    getParentRoute: () => AdminLayoutRoute,
  } as any)
const AdminLayoutOrdersIndexRoute = AdminLayoutOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutInventoryIndexRoute =
  AdminLayoutInventoryIndexRouteImport.update({
    id: '/inventory/',
    path: '/inventory/',
    getParentRoute: () => AdminLayoutRoute,
  } as any)
const AdminLayoutCategoriesIndexRoute =
  AdminLayoutCategoriesIndexRouteImport.update({
    id: '/categories/',
    path: '/categories/',
    getParentRoute: () => AdminLayoutRoute,
  } as any)
const AdminLayoutProductsIdRoute = AdminLayoutProductsIdRouteImport.update({
  id: '/products/$id',
  path: '/products/$id',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutOrdersIdRoute = AdminLayoutOrdersIdRouteImport.update({
  id: '/orders/$id',
  path: '/orders/$id',
  getParentRoute: () => AdminLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/account': typeof AppAccountRoute
  '/cart': typeof AppCartRoute
  '/checkout': typeof AppCheckoutRoute
  '/track': typeof AppTrackRoute
  '/admin': typeof AdminLayoutRouteWithChildren
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/verify-otp': typeof AuthVerifyOtpRoute
  '/orders/$id': typeof AppOrdersIdRoute
  '/products/$slug': typeof AppProductsSlugRoute
  '/orders/': typeof AppOrdersIndexRoute
  '/products/': typeof AppProductsIndexRoute
  '/admin/': typeof AdminLayoutIndexRoute
  '/admin/orders/$id': typeof AdminLayoutOrdersIdRoute
  '/admin/products/$id': typeof AdminLayoutProductsIdRoute
  '/admin/categories/': typeof AdminLayoutCategoriesIndexRoute
  '/admin/inventory/': typeof AdminLayoutInventoryIndexRoute
  '/admin/orders/': typeof AdminLayoutOrdersIndexRoute
  '/admin/products/': typeof AdminLayoutProductsIndexRoute
  '/admin/users/': typeof AdminLayoutUsersIndexRoute
}
export interface FileRoutesByTo {
  '/account': typeof AppAccountRoute
  '/cart': typeof AppCartRoute
  '/checkout': typeof AppCheckoutRoute
  '/track': typeof AppTrackRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/verify-otp': typeof AuthVerifyOtpRoute
  '/': typeof AppIndexRoute
  '/orders/$id': typeof AppOrdersIdRoute
  '/products/$slug': typeof AppProductsSlugRoute
  '/orders': typeof AppOrdersIndexRoute
  '/products': typeof AppProductsIndexRoute
  '/admin': typeof AdminLayoutIndexRoute
  '/admin/orders/$id': typeof AdminLayoutOrdersIdRoute
  '/admin/products/$id': typeof AdminLayoutProductsIdRoute
  '/admin/categories': typeof AdminLayoutCategoriesIndexRoute
  '/admin/inventory': typeof AdminLayoutInventoryIndexRoute
  '/admin/orders': typeof AdminLayoutOrdersIndexRoute
  '/admin/products': typeof AdminLayoutProductsIndexRoute
  '/admin/users': typeof AdminLayoutUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/account': typeof AppAccountRoute
  '/_app/cart': typeof AppCartRoute
  '/_app/checkout': typeof AppCheckoutRoute
  '/_app/track': typeof AppTrackRoute
  '/admin/_layout': typeof AdminLayoutRouteWithChildren
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/verify-otp': typeof AuthVerifyOtpRoute
  '/_app/': typeof AppIndexRoute
  '/_app/orders/$id': typeof AppOrdersIdRoute
  '/_app/products/$slug': typeof AppProductsSlugRoute
  '/_app/orders/': typeof AppOrdersIndexRoute
  '/_app/products/': typeof AppProductsIndexRoute
  '/admin/_layout/': typeof AdminLayoutIndexRoute
  '/admin/_layout/orders/$id': typeof AdminLayoutOrdersIdRoute
  '/admin/_layout/products/$id': typeof AdminLayoutProductsIdRoute
  '/admin/_layout/categories/': typeof AdminLayoutCategoriesIndexRoute
  '/admin/_layout/inventory/': typeof AdminLayoutInventoryIndexRoute
  '/admin/_layout/orders/': typeof AdminLayoutOrdersIndexRoute
  '/admin/_layout/products/': typeof AdminLayoutProductsIndexRoute
  '/admin/_layout/users/': typeof AdminLayoutUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/cart'
    | '/checkout'
    | '/track'
    | '/admin'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/auth/verify-otp'
    | '/orders/$id'
    | '/products/$slug'
    | '/orders/'
    | '/products/'
    | '/admin/'
    | '/admin/orders/$id'
    | '/admin/products/$id'
    | '/admin/categories/'
    | '/admin/inventory/'
    | '/admin/orders/'
    | '/admin/products/'
    | '/admin/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/account'
    | '/cart'
    | '/checkout'
    | '/track'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/auth/verify-otp'
    | '/'
    | '/orders/$id'
    | '/products/$slug'
    | '/orders'
    | '/products'
    | '/admin'
    | '/admin/orders/$id'
    | '/admin/products/$id'
    | '/admin/categories'
    | '/admin/inventory'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/users'
  id:
    | '__root__'
    | '/_app'
    | '/_app/account'
    | '/_app/cart'
    | '/_app/checkout'
    | '/_app/track'
    | '/admin/_layout'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/auth/verify-otp'
    | '/_app/'
    | '/_app/orders/$id'
    | '/_app/products/$slug'
    | '/_app/orders/'
    | '/_app/products/'
    | '/admin/_layout/'
    | '/admin/_layout/orders/$id'
    | '/admin/_layout/products/$id'
    | '/admin/_layout/categories/'
    | '/admin/_layout/inventory/'
    | '/admin/_layout/orders/'
    | '/admin/_layout/products/'
    | '/admin/_layout/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AdminLayoutRoute: typeof AdminLayoutRouteWithChildren
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthVerifyOtpRoute: typeof AuthVerifyOtpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/auth/verify-otp': {
      id: '/auth/verify-otp'
      path: '/auth/verify-otp'
      fullPath: '/auth/verify-otp'
      preLoaderRoute: typeof AuthVerifyOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_layout': {
      id: '/admin/_layout'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/track': {
      id: '/_app/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof AppTrackRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/checkout': {
      id: '/_app/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof AppCheckoutRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cart': {
      id: '/_app/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof AppCartRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/account': {
      id: '/_app/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AppAccountRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/_layout/': {
      id: '/admin/_layout/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminLayoutIndexRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/_app/products/': {
      id: '/_app/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof AppProductsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orders/': {
      id: '/_app/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof AppOrdersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/products/$slug': {
      id: '/_app/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof AppProductsSlugRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orders/$id': {
      id: '/_app/orders/$id'
      path: '/orders/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof AppOrdersIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/_layout/users/': {
      id: '/admin/_layout/users/'
      path: '/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AdminLayoutUsersIndexRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/products/': {
      id: '/admin/_layout/products/'
      path: '/products'
      fullPath: '/admin/products/'
      preLoaderRoute: typeof AdminLayoutProductsIndexRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/orders/': {
      id: '/admin/_layout/orders/'
      path: '/orders'
      fullPath: '/admin/orders/'
      preLoaderRoute: typeof AdminLayoutOrdersIndexRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/inventory/': {
      id: '/admin/_layout/inventory/'
      path: '/inventory'
      fullPath: '/admin/inventory/'
      preLoaderRoute: typeof AdminLayoutInventoryIndexRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/categories/': {
      id: '/admin/_layout/categories/'
      path: '/categories'
      fullPath: '/admin/categories/'
      preLoaderRoute: typeof AdminLayoutCategoriesIndexRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/products/$id': {
      id: '/admin/_layout/products/$id'
      path: '/products/$id'
      fullPath: '/admin/products/$id'
      preLoaderRoute: typeof AdminLayoutProductsIdRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/orders/$id': {
      id: '/admin/_layout/orders/$id'
      path: '/orders/$id'
      fullPath: '/admin/orders/$id'
      preLoaderRoute: typeof AdminLayoutOrdersIdRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
  }
}

interface AppRouteChildren {
  AppAccountRoute: typeof AppAccountRoute
  AppCartRoute: typeof AppCartRoute
  AppCheckoutRoute: typeof AppCheckoutRoute
  AppTrackRoute: typeof AppTrackRoute
  AppIndexRoute: typeof AppIndexRoute
  AppOrdersIdRoute: typeof AppOrdersIdRoute
  AppProductsSlugRoute: typeof AppProductsSlugRoute
  AppOrdersIndexRoute: typeof AppOrdersIndexRoute
  AppProductsIndexRoute: typeof AppProductsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountRoute: AppAccountRoute,
  AppCartRoute: AppCartRoute,
  AppCheckoutRoute: AppCheckoutRoute,
  AppTrackRoute: AppTrackRoute,
  AppIndexRoute: AppIndexRoute,
  AppOrdersIdRoute: AppOrdersIdRoute,
  AppProductsSlugRoute: AppProductsSlugRoute,
  AppOrdersIndexRoute: AppOrdersIndexRoute,
  AppProductsIndexRoute: AppProductsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AdminLayoutRouteChildren {
  AdminLayoutIndexRoute: typeof AdminLayoutIndexRoute
  AdminLayoutOrdersIdRoute: typeof AdminLayoutOrdersIdRoute
  AdminLayoutProductsIdRoute: typeof AdminLayoutProductsIdRoute
  AdminLayoutCategoriesIndexRoute: typeof AdminLayoutCategoriesIndexRoute
  AdminLayoutInventoryIndexRoute: typeof AdminLayoutInventoryIndexRoute
  AdminLayoutOrdersIndexRoute: typeof AdminLayoutOrdersIndexRoute
  AdminLayoutProductsIndexRoute: typeof AdminLayoutProductsIndexRoute
  AdminLayoutUsersIndexRoute: typeof AdminLayoutUsersIndexRoute
}

const AdminLayoutRouteChildren: AdminLayoutRouteChildren = {
  AdminLayoutIndexRoute: AdminLayoutIndexRoute,
  AdminLayoutOrdersIdRoute: AdminLayoutOrdersIdRoute,
  AdminLayoutProductsIdRoute: AdminLayoutProductsIdRoute,
  AdminLayoutCategoriesIndexRoute: AdminLayoutCategoriesIndexRoute,
  AdminLayoutInventoryIndexRoute: AdminLayoutInventoryIndexRoute,
  AdminLayoutOrdersIndexRoute: AdminLayoutOrdersIndexRoute,
  AdminLayoutProductsIndexRoute: AdminLayoutProductsIndexRoute,
  AdminLayoutUsersIndexRoute: AdminLayoutUsersIndexRoute,
}

const AdminLayoutRouteWithChildren = AdminLayoutRoute._addFileChildren(
  AdminLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AdminLayoutRoute: AdminLayoutRouteWithChildren,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthVerifyOtpRoute: AuthVerifyOtpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
